### ISSUE TITLE
Load all repos then load the filters/buttons

### ISSUE THREAD

**Issue by lauracowen** [WASdev/wasdev.github.io#9]
Currently, the list of repos is displayed only after the filter buttons have been generated. This makes the page quite slow to load. Also, a side-effect is that when filters are broken, nothing loads. Better if everything loads then the filters are generated?

**Comment by BillyD73** [comment]
Looked into this and the load order is required for the automatic filter button generation feature - tested the site and the script takes a fraction of a second to load; the github api request is what is taking time to load (approx 3-4 seconds) and therefore can't be fixed. Added a loading spinner to the site to make the entire process a lot more fluid.
